#! /bin/bash

# This script start process which listen the specified port 
# and echo the received data to the output

port=$1

if [ -z "$port" ] || [ "$port" = "--hep" ] ; then
    echo "Usage: $0 <port>"
    return
fi

# Check nc version
nc_version=$(nc -h 2>&1 | grep 'Ncat version')

if [[ $nc_version ]]; then
    # Ncat version
    nc -l -p $port -v | while read line; do
        echo $line
    done
else
    # Traditional nc version
    nc -l $port -v | while read line; do
        echo $line
    done
fi

