#!/usr/bin/env bash

COMMAND_DESCRIPTION="Remove empty lines"

COMMAND_HELP="\
Remove empty lines from stdin.
Usage:
    :lines:where:not-empty
"

_do_command() {
    # Show help on --help
    if [[ "$1" == "--help" || "$1" == "help" ]]; then
        echo "$COMMAND_HELP"
        return
    fi

    local condition="$1"

    while IFS= read -r line; do
        if [[ ! -z "$line" ]]; then
            echo "$line"
        fi
    done
}

_do_command "$@"
