#!/usr/bin/env bash

COMMAND_DESCRIPTION="Remove lines that contain a text"

COMMAND_HELP="\
Remove lines that contain a text.
Usage:
    :lines:where:not-contains <text>
Arguments:
    text: Text to search for
Example:
    :lines:where:not-contains 'hello|hi'
"

_do_command() {
    # Show help on --help
    if [[ "$1" == "--help" || "$1" == "help" ]]; then
        echo "$COMMAND_HELP"
        return
    fi

    local condition="$1"

    while IFS= read -r line; do
        if [[ "$line" != *"$condition"* ]]; then
            echo "$line"
        fi
    done
}

_do_command "$@"
