#!/usr/bin/env bash

COMMAND_DESCRIPTION="Check SSH access to GitHub."

COMMAND_HELP="\
Check SSH access to GitHub with the default user in the current directory.
Display used username if the access is successful.

Usage: 
    :git:check-ssh-access [url]
"

_do_command() {
    if [[ "$1" == "--help" || "$1" == "help" ]]; then
        echo "$COMMAND_HELP"
        return
    fi

    local url="$1"
    [ -z "$url" ] && url="github.com"

    ssh -T git@$url
}

_do_command $@
