#!/bin/bash

COMMAND_DESCRIPTION="Generate GitHub 'no-reply' email address."

COMMAND_HELP="\
Generate GitHub 'no-reply' email address.
Usage: 
    :git:github-no-reply-email <username>
"

_do_command() {
    if [[ "$1" = "--help" ]]; then
        echo "$COMMAND_HELP"
        return
    fi

    local username="$1"
    if [ -z "$username" ]; then
        echo "Please provide a GitHub username."
        return 1
    fi

    local user_info=$(curl -s "https://api.github.com/users/$username")
    local user_id=$(echo "$user_info" | grep '"id"' | head -1 | tr -dc '0-9')
    echo "${user_id}+${username}@users.noreply.github.com"
}

_do_command $@
