#!/usr/bin/env bash
#set -euo pipefail

COMMAND_DESCRIPTION="Update project git GitHub account."

COMMAND_HELP="\
Update git settings for the project to use specified GitHub account.
Usage: 
    :git:set-git-user-for-project <github_account> <email> [project_dir]
"

_do_command() {
    if [[ "$1" == "--help" || "$1" == "help" ]]; then
        echo "$COMMAND_HELP"
        return
    fi

    # Variables
    local github_account=$1
    local email=$2
    local project_dir=$3

    # Check if the GitHub account is provided
    if [ -z "$github_account" ]; then
        echo "GitHub account is required"
        exit 1
    fi

    # Check if the email is provided
    if [ -z "$email" ]; then
        email=$(eval ": :git:github-no-reply-email '$github_account'")
        echo "Email is not specified, use no-reply github address: $email"
    fi

    # Check if the project directory is provided or use the current directory
    [ -z "$project_dir" ] && project_dir="."

    # Check if the project directory exists
    if [ ! -d "$project_dir" ]; then
        echo "Project directory does not exist: $project_dir"
        exit 1
    fi

    # Update the git settings for the project
    if [ "$project_dir" != "." ]; then
        cd "$project_dir"
    fi

    git config user.name "$github_account"
    git config user.email "$email"

    echo "Git settings updated for the project: $project_dir"
}

_do_command $@

