#!/usr/bin/env bash
# set -euo pipefail

# Open the bashrc file in the default text editor

FILE_TO_OPEN="$HOME/.bashrc"
FILE_TITLE="bash configuration file"

source "$LETDEV_HOME/commands/:/config/.edit_config.sh"
_edit_config "$FILE_TO_OPEN" "$FILE_TITLE"
