#!/usr/bin/env bash
# set -euo pipefail

# Open the privoxy configuration file in the default text editor

FILE_TO_OPEN="/usr/local/etc/privoxy/config"
FILE_TITLE="privoxy configuration file"

source ./.edit_config.sh
_edit_config "$FILE_TO_OPEN" "$FILE_TITLE"
