#!/usr/bin/env bash
# set -euo pipefail

# Open ssh config file in the default text editor

FILE_TO_OPEN="/etc/ssh/sshd_config"
FILE_TITLE="ssh server configuration file"

source ./.edit_config.sh
_edit_config "$FILE_TO_OPEN" "$FILE_TITLE"
