#!/usr/bin/env bash
# set -euo pipefail

# Open vim config file in the default text editor

FILE_TO_OPEN="$HOME/.vimrc"
FILE_TITLE="vim configuration file"

source ./.edit_config.sh
_edit_config "$FILE_TO_OPEN" "$FILE_TITLE"
