#!/usr/bin/env bash
# set -euo pipefail

# Open the bashrc file in the default text editor

FILE_TO_OPEN="$HOME/.zshrc"
FILE_TITLE="zsh configuration file"

source ./.edit_config.sh
_edit_config "$FILE_TO_OPEN" "$FILE_TITLE"
