#!/usr/bin/env bash

COMMAND_DESCRIPTION="Rerutn data received on a specified port back to the sender"

COMMAND_HELP="\
Start a process which listens on the specified port
    and sends the received data back to the sender.
Usage:
    :net:http:listener:ping <port>
Example:
    :net:http:listener:ping 8080
"

_do_command() {
    if [ "$1" = "--help" ] || [ "$1" = "help" ]; then
        echo "$COMMAND_HELP"
        return
    fi

    local port=$1

    if [ -z "$port" ] || [ "$port" = "--hep" ] ; then
        echo "Usage: $0 <port>"
        return
    fi

    DELIM="--------------------- Connection closed. Waiting for new connection... ----------------------"

    # Check nc version
    nc_version=$(nc -h 2>&1 | grep 'Ncat version')

    while true; do
        if [[ $nc_version ]]; then
            # Ncat version
            sudo nc -l -p $port -v | while read line; do
                echo $line | nc localhost $port
            done
        else
            # Traditional nc version
            sudo nc -l $port -v | while read line; do
                echo $line | nc localhost $port 
            done
        fi
    done
}

_do_command "$@"
