#!/bin/bash

[ -n "${BASH_SOURCE[0]}" ] && SCRIPT_PATH="${BASH_SOURCE[0]}" || SCRIPT_PATH="$0"
APP_FOLDER_PATH=`dirname $SCRIPT_PATH`
source "$APP_FOLDER_PATH/.env"

pushd "$ALIAS_GUN_APP_FOLDER_PATH" > /dev/null

# System aliases
CMD=`./echo-add-folder-script './aliases'` && eval "$CMD"

# User aliases
[ -d "$ALIAS_GUN_ALIASES_FOLDER_PATH" ] && CMD=`./echo-add-folder-script "$ALIAS_GUN_ALIASES_FOLDER_PATH"` && eval "$CMD"

# Default command alias
alias :="source $ALIAS_GUN_APP_FOLDER_PATH/default"

popd > /dev/null
