#!/bin/bash

APP_FOLDER_NAME="$LETDEV_PATH"

LIST_MODE=false
if [ "$1" = "--list" ]; then
    LIST_MODE=true
    shift
fi

COLORED=''
[[ $TERM =~ (color|ansi|xterm|rxvt) && $LIST_MODE = false ]] && COLORED='true'

CMD=''
[ -n "$1" ] && CMD=`echo "$@" | tr " " "/"`
CMD="$LETDEV_SYMBOL$CMD"
#echo "cmd: $CMD"

# COMMAND_LIST=`alias | sed 's/^alias //' | grep "^$CMD" | grep -v "$APP_FOLDER_NAME/default"`
pushd "$LETDEV_PATH/commands" > /dev/null
COMMAND_LIST=$(find . -type d -print -o -type f -print -o -type l -print)
popd > /dev/null
#echo "000: $COMMAND_LIST"

# Fix command start symbols
COMMAND_LIST=`echo "$COMMAND_LIST" | sed 's/^\.//' | sed "s/^\//$LETDEV_SYMBOL/" | sed "s/^$LETDEV_SYMBOL$LETDEV_SYMBOL$LETDEV_SYMBOL/$LETDEV_SYMBOL$LETDEV_SYMBOL/"`
#echo "001: $COMMAND_LIST"

# Remove hidden files and folders and empty commands
COMMAND_LIST=`echo "$COMMAND_LIST" | grep -ve "^$LETDEV_SYMBOL\." | grep -ve '/\.' | grep -v "^[[:space:]]*$"`
#echo "COMMAND_LIST: $COMMAND_LIST"

#EXISTS=`echo $COMMAND_LIST | grep "^$CMD="`
EXISTS=`echo $COMMAND_LIST | grep "$CMD"`
# echo "exists: $EXISTS"

# [ -n "$EXISTS" ] && eval $CMD && return

#echo "not exists"

LIST=`echo "$COMMAND_LIST" | grep "$CMD"`
#echo "0: $LIST"

#LIST=`echo "$LIST" | sed 's/=.*//'`
#echo "1: $LIST"
#LIST=`echo "$LIST" | grep -E -o "^$CMD$LETDEV_SYMBOL?[^$LETDEV_SYMBOL]*$LETDEV_SYMBOL?"`
#echo "2: $LIST"

if [ -n "$COLORED" ]; then
    LIST=`echo "$LIST" | sed "s/$LETDEV_SYMBOL$/\*/" | sed "s/^.*$LETDEV_SYMBOL/  /" | awk '{ printf "%-20s\n", $0 }' | sed 's/\*[ ]*$/&(...)/' | sed 's/\*//' | awk '{ printf "%-26s\n", $0 }'`
    #echo "3: $LIST"
    LIST=`echo "$LIST" | uniq | sort -t $'(' -k 2,2r -k 1,1n`
    LIST=`echo "$LIST" | awk '{gsub(/.*\(.*/,"\033[1;44m&\033[0m"); print}' | awk '{gsub(/^[^(]*$/,"\033[32;44m&\033[0m"); print}'`
fi

echo "$LIST"
