#!/bin/bash

COMMAND_DESCRIPTION="Firewall management"

COMMAND_HELP="\
Firewall management
Usage:
    :net:firewall [status|start|stop|restart|enable|disable|config]
    If no command is provided, status will be used
"

_do_config() {
    local FILE_TO_OPEN="/etc/ufw/ufw.conf"

    if [ ! -f "$FILE_TO_OPEN" ]; then
        echo "$FILE_TO_OPEN was not found"
        return
    fi

    local hash_before=$(sha256sum "$FILE_TO_OPEN")
    : :config:firewall
    local hash_after=$(sha256sum "$FILE_TO_OPEN")

    if [[ "$hash_before" != "$hash_after" ]]; then
        echo "Ufw configuration updated"

        # Reload Ufw if it is running
        if sudo systemctl is-active --quiet ufw; then
            echo "Ufw service is running, reloading..."
            sudo systemctl reload ufw
            echo "Ufw service reloaded"
        fi
    else
        echo "Ufw configuration was not changed"
    fi
}

_do_command() {
    if [ "$1" = "--help" ] || [ "$1" = "help" ]; then
        echo "$COMMAND_HELP"
        return
    fi

    # Check operating system: only support Ubuntu
    if [ ! -f /etc/os-release ]; then
        echo "Operating system not supported"
        return
    fi


    local command=$1
    [ -z "$command" ] && command="status"

    case $command in
        status)
            sudo ufw status
            ;;
        start)
            sudo ufw enable
            ;;
        stop)
            sudo ufw disable
            ;;
        restart)
            sudo ufw disable
            sudo ufw enable
            ;;
        enable)
            sudo ufw enable
            ;;
        disable)
            sudo ufw disable
            ;;
        config)
            _do_config
            ;;
        *)
            echo "Invalid command"
            ;;
    esac
}

_do_command $@
