#!/usr/bin/env bash

COMMAND_DESCRIPTION="Expose local HTTP server to the Internet"

COMMAND_HELP="\
Expose local HTTP server to the Internet via http://serveo.net service.
Usage:
    :net:internet-access-to-local-http <port>
Example:
    :net:internet-access-to-local-http.sh 3000
"

_do_command() {
    if [ "$1" = "--help" ] || [ "$1" = "help" ]; then
        echo "$COMMAND_HELP"
        return
    fi

    local port=$1

    [ -z "$port" ] && echo -n "Enter the port number: " && read port

    if [ "$port" -lt 1 ] || [ "$port" -gt 65535 ]; then
        echo "Invalid port number"
        return
    fi

    if [ -z "$(which ssh)" ]; then
        echo "Install ssh"
        sudo apt update -y
        sudo apt install ssh -y
        echo ""
        echo "SSH installed successfully"
    else
        echo "SSH is already installed"
    fi

    ssh -R "80:localhost:$port" serveo.net
}

_do_command "$@"
