#!/bin/bash

# Print ip address of the machine

# ip addr show eth0 | grep inet | awk '{ print $2; }' | sed 's/\/.*$//'

_do_command_info_ip() {
    local OS="$(uname)"

    local IP_ADDRESS=""
    if [[ "$OS" == "Linux" ]]; then
        IP_ADDRESS=$(hostname -I | awk '{print $1}')
        echo 999
    elif [[ "$OS" == "Darwin" ]]; then
        IP_ADDRESS=$(ifconfig | grep 'inet ' | grep -v '127.0.0.1' | awk '{print $2}' | head -n 1)
    else
        echo "Unsupported OS: $OS"
        return
    fi

    local IP_ADDRESS_EXTERNAL=$(curl -s ifconfig.me)

    echo "Current machine IP"
    echo "internal: $IP_ADDRESS"
    echo "external: $IP_ADDRESS_EXTERNAL"
}

_do_command_info_ip
