#!/bin/bash

# ip addr show eth0 | grep inet | awk '{ print $2; }' | sed 's/\/.*$//'

COMMAND_DESCRIPTION="Display local and external IP addresses of the machine"

COMMAND_HELP="\
Display local and external IP addresses of the machine
Usage: 
    :net:ip
"

_do_command() {
    if [ "$1" = "--help" ] || [ "$1" = "help" ]; then
        echo "$COMMAND_HELP"
        return
    fi

    local OS="$(uname)"

    local IP_ADDRESS=""
    if [[ "$OS" == "Linux" ]]; then
        IP_ADDRESS=$(hostname -I | awk '{print $1}')
    elif [[ "$OS" == "Darwin" ]]; then
        IP_ADDRESS=$(ifconfig | grep 'inet ' | grep -v '127.0.0.1' | awk '{print $2}' | head -n 1)
    else
        echo "Unsupported OS: $OS"
        return
    fi

    local IP_ADDRESS_EXTERNAL=$(curl -s ifconfig.me)

    # local DOCKER_HOST_IP=$(ip addr show docker0 | grep 'inet ' | awk '{print $2}' | sed 's/\/.*$//')
    local DOCKER_HOST_IP=$(ip -4 addr show docker0 | grep -Po 'inet \K[\d.]+')

    echo "Current machine IP"
    echo "internal: $IP_ADDRESS"
    echo "external: $IP_ADDRESS_EXTERNAL"
    echo "docker host: $DOCKER_HOST_IP"
}

_do_command $@
