#!/bin/bash

# List all listening ports

# Help
if [ "$1" == "--help" ]; then
    echo "Usage: $0 [lsof|netstat|ss]"
    exit 0
fi

method=$1

if [[ -z "$method" || "$method" == "lsof" ]]; then
    sudo lsof -P -iTCP -sTCP:LISTEN
    return
elif [ "$method" == "netstat" ]; then
    netstat -tuln
    exit 0
elif [ "$method" == "ss" ]; then
    ss -tuln
    return
else
    echo "Invalid method"
    echo "Usage: $0 [lsof|netstat|ss]"
    return
fi
