#!/bin/bash

COMMAND_DESCRIPTION="List all listening ports."

COMMAND_HELP="\
List all listening ports.
Usage:
    :net:ls [lsof|netstat|ss]
"

_do_command() {
    if [ "$1" = "--help" ] || [ "$1" = "help" ]; then
        echo "$COMMAND_HELP"
        return
    fi

    method=$1

    if [[ -z "$method" || "$method" == "lsof" ]]; then
        sudo lsof -P -iTCP -sTCP:LISTEN
        return
    elif [ "$method" == "netstat" ]; then
        netstat -tuln
        return
    elif [ "$method" == "ss" ]; then
        ss -tuln
        return
    else
        echo "Invalid method"
        echo "Usage: $0 [lsof|netstat|ss]"
        return
    fi
}

_do_command $@
