#!/usr/bin/env bash

COMMAND_DESRIPTION="Make a request to the Gemini API"

COMMAND_HELP="\
This script is used to make a request to the Gemini API.

Usage: 
    :ai:gemini <query>

Example:
    :ai:gemini What is the meaning of life?
"


_do_command() {
    if [[ "$1" = "help" ]] || [[ "$1" = "--help" ]]; then
        echo "$COMMAND_HELP"
        return
    fi

    local query="$@"
    shift
    [[ -z "$query" ]] && echo "Error: query is required" && return

    # echo "Query: $query"

    # Load API key from .env file
    local ENV_FILE="$LETDEV_HOME/profiles/$LETDEV_PROFILE/.env"
    [ -f "$ENV_FILE" ] && source "$ENV_FILE"
    local api_key="$gemini_api_key" || "$GEMINI_API_KEY"

    # role: user, model
    local request_body="{ \
        \"contents\": [
            { \"role\" : \"user\", \"parts\": [ { \"text\" : \"$query\" } ] }
        ]
    }"

    # echo "Request body: $request_body"

    local response=$(curl -s "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=$api_key" \
        -H "Content-Type: application/json" \
        -X POST \
        -d "$request_body"
    )

    # echo "Response: $response"

    # Check if the response is an error
    if [[ "$response" == *"error"* ]]; then
        echo -n "Error: "
        echo "$response" | :json:extract 'error.message'
        return
    fi

    echo "$response" | :json:extract 'candidates[0].content.parts[*].text' | :markdown
}

_do_command "$@"
