#!/usr/bin/env bash
#set -euo pipefail

# Update git settings for the project with the GitHub account

# Help
if [ "$1" == "--help" ]; then
    echo "Usage: $0 <github_account> <email> [project_dir]"
    exit 0
fi

# Variables
github_account=$1
email=$2
project_dir=$3

# Check if the GitHub account is provided
if [ -z "$github_account" ]; then
    echo "GitHub account is required"
    exit 1
fi

# Check if the email is provided
if [ -z "$email" ]; then
    echo "Email is required"
    exit 1
fi

git config --global user.name "$github_account"
git config --global user.email "$email"

echo "Git settings updated globally"
