#!/usr/bin/env bash
# set -euo pipefail

COMMAND_DESCRIPTION="Edit docker daemon configuration"
COMMAND_HELP="\
Open docker daemon configuration file in the preferred text editor
"

_do_command() {
    local FILE_TO_OPEN=""

    OS=$(uname)
    if [[ "$OS" == "Linux" ]]; then
        FILE_TO_OPEN="/etc/docker/daemon.json"
    elif [[ "$OS" == "Darwin" ]]; then
        FILE_TO_OPEN="$HOME/Library/Group Containers/group.com.docker/settings.json"
    else
        echo "Unsupported operating system: $OS"
        return 1
    fi

    source "$LETDEV_HOME/commands/config/.edit_config.sh"

    echo "Editing Docker daemon configuration file: $FILE_TO_OPEN"

    _edit_config "$FILE_TO_OPEN" $@
    local isModified=$?

    # If config was modified, ask to restart docker service
    if [[ $isModified -eq 0 ]]; then
        echo "Docker daemon configuration was not modified."
    else
        if :confirm "Docker daemon configuration was modified. Do you want to restart the Docker service?"; then
            if [[ "$OS" == "Linux" ]]; then
                sudo systemctl restart docker
            elif [[ "$OS" == "Darwin" ]]; then
                osascript -e 'quit app "Docker"'
                open -a Docker
            fi
        fi
    fi
}

_do_command "$@"
