#!/usr/bin/env bash
# set -euo pipefail

COMMAND_DESCRIPTION="Edit firewall configuration"
COMMAND_HELP="\
Open firewall service configuration file in the preferred text editor.
"

_do_command() {
    local FILE_TO_OPEN="/etc/ufw/ufw.conf"

    source "$LETDEV_HOME/commands/config/.edit_config.sh"
    _edit_config "$FILE_TO_OPEN" $@
    return $?
}

_do_command "$@"
