#!/usr/bin/env bash
# set -euo pipefail

COMMAND_DESCRIPTION="Edit nginx configuration"
COMMAND_HELP="\
Open nginx service configuration file in the preferred text editor
"

_do_command() {
    local FILE_TO_OPEN="/etc/nginx/nginx.conf"

    source "$LETDEV_HOME/commands/config/.edit_config.sh"
    _edit_config "$FILE_TO_OPEN" $@
    return $?
}

_do_command "$@"
