#!/usr/bin/env bash
# set -euo pipefail

COMMAND_DESCRIPTION="Edit pry configuration"
COMMAND_HELP="\
Open pry configuration file in the preferred text editor
"

_do_command() {
    local FILE_TO_OPEN="$HOME/.pryrc"

    source "$LETDEV_HOME/commands/config/.edit_config.sh"
    _edit_config "$FILE_TO_OPEN" $@
    return $?
}

_do_command "$@"
