#!/usr/bin/env bash
# set -euo pipefail

COMMAND_DESCRIPTION="Edit sshd service configuration"
COMMAND_HELP="\
Open sshd service configuration file in the preferred text editor
"

_do_command() {
    local FILE_TO_OPEN="/etc/ssh/sshd_config"

    source "$LETDEV_HOME/commands/config/.edit_config.sh"
    _edit_config "$FILE_TO_OPEN" $@ --sudo
    return $?
}

_do_command "$@"
