#!/usr/bin/env bash
# set -euo pipefail

COMMAND_DESCRIPTION="Edit Tinyproxy configuration"
COMMAND_HELP="\
Open Tinyproxy configuration file in the preferred text editor.
"

_do_command() {
    # Use file path depending on the OS
    local FILE_TO_OPEN=""
    if [ "$(uname)" == "Darwin" ]; then
        FILE_TO_OPEN="/usr/local/etc/tinyproxy/tinyproxy.conf"
    elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
        FILE_TO_OPEN="/etc/tinyproxy/tinyproxy.conf"
    else
        echo "Unsupported OS"
        return 1
    fi

    source "$LETDEV_HOME/commands/config/.edit_config.sh"
    _edit_config "$FILE_TO_OPEN" $@
    return $?
}

_do_command "$@"
