#!/usr/bin/env bash
# set -euo pipefail

COMMAND_DESCRIPTION="Edit zsh configuration"
COMMAND_HELP="\
Open zsh configuration file in the preferred text editor
"

_do_command() {
    local FILE_TO_OPEN="$HOME/.zshrc"

    source "$LETDEV_HOME/commands/config/.edit_config.sh"
    _edit_config "$FILE_TO_OPEN" $@
    return $?
}

_do_command "$@"
