#!/bin/bash

alias_name="$1"
[ -z "$alias_name" ] && alias_name=$(basename $PWD)

location="$2"
[ -z "$location" ] && location="$PWD"

script_name="$alias_name"
script_path="$LETDEV_HOME/profiles/$LETDEV_PROFILE/cd/$script_name"

echo "Add alias ':cd:$alias_name' which will change directory to '$location'"

[ -f "$script_path" ] && echo "Alias with the name ':cd:$alias_name' already exists" && return

mkdir -p "$LETDEV_HOME/profiles/$LETDEV_PROFILE/cd"

touch "$script_path"
chmod +x $script_path

echo "#! /bin/bash" > "$script_path"
echo "" >> "$script_path"
echo "cd $location" >> "$script_path"

eval ::reload
