#!/usr/bin/env bash

COMMAND_DESCRIPTION="Echo data received on a specified port"

COMMAND_HELP="\
Start a process which listens on the specified port and echoes the received data to the output.
Usage:
    :net:http:listener <port>
Example:
    :net:http:listener 8080
"

_do_command() {

    if [ "$1" = "--help" ] || [ "$1" = "help" ]; then
        echo "$COMMAND_HELP"
        return
    fi

    local port=$1

    if [ -z "$port" ] || [ "$port" = "--hep" ] ; then
        echo "Usage: $0 <port>"
        return
    fi

    DELIM="--------------------- Connection closed. Waiting for new connection... ----------------------"

    # Check nc version
    nc_version=$(nc -h 2>&1 | grep 'Ncat version')

    while true; do
        if [[ $nc_version ]]; then
            # Ncat version
            sudo nc -l -p $port -v | while read line; do
                echo $line
            done
        else
            # Traditional nc version
            sudo nc -l $port -v | while read line; do
                echo $line
            done
        fi

        echo "$DELIM"
    done
}

_do_command "$@"
