#!/bin/bash

COMMAND_DESCRIPTION="Ask user for input."

COMMAND_HELP="\
Ask user for input.
Usage:
    :ask <message>
Example:
    :ask 'What is your name?'
"

_do_command() {
    # Show help on --help
    [[ "$1" == "--help" || "$1" == "help" ]] && echo "$COMMAND_HELP" && return

    local message="$@"
    
    local value
    if [[ -n $ZSH_VERSION ]]; then
        # echo -n "$message: "
        # read value
        read "?Enter $message: " value
    elif [[ -n $BASH_VERSION ]]; then
        read -p "$message: " value
    else
        echo "Error: Unsupported shell"
        return
    fi
   
    echo $value
}

_do_command $@
