#!/bin/bash

COMMAND_DESCRIPTION="Ask user for input."

COMMAND_HELP="\
Ask user for input.
Usage:
    :ask <message> [default_value]
Example:
    :ask 'What is your name?' 'John Doe'
"

_do_command() {
    # Show help on --help
    [[ "$1" == "--help" || "$1" == "help" ]] && echo "$COMMAND_HELP" && return

    local message="$1"
    [[ -z $message ]] && echo "Error: Message is required" && return

    local default_value="$2"
    [[ -n $default_value ]] && message="$message [$default_value]"
    
    local value
    if [[ -n $ZSH_VERSION ]]; then
        # echo -n "$message: "
        # read value
        read "?Enter $message: " value
    elif [[ -n $BASH_VERSION ]]; then
        read -p "$message: " value
    else
        echo "Error: Unsupported shell"
        return
    fi

    [[ -z $value ]] && value="$default_value"
   
    echo $value
}

_do_command $@
