#!/usr/bin/env bash

COMMAND_DESCRIPTION="Simple confirm dialog"

COMMAND_HELP="\
Simple confirm dialog.
Usage:
    :confirm <message>
Example:
    :confirm 'Do you want to continue?' && echo 'Yes' || echo 'No'
"

_do_command() {
    # Show help on --help
    [[ "$1" == "--help" || "$1" == "help" ]] && echo "$COMMAND_HELP" && return

    local message="$@"
    [ -z "$message" ] && message="[y/n]: " || message="$message [y/n]: "

    local result
    if [[ $SHELL == *"zsh"* ]]; then
        # vared -p "$message" 'result'
        echo -n "$message"
        read -r result
    else
        read -p "$message" result
    fi

    [ "$result" == "y" ]
}

_do_command $@
