#!/usr/bin/env bash

COMMAND_DESCRIPTION="Simple confirm dialog"

COMMAND_HELP="\
Simple confirm dialog.
Usage:
    :confirm <message>
Example:
    :confirm 'Do you want to continue?' && echo 'Yes' || echo 'No'
"

_do_command() {
    # Show help on --help
    [[ "$1" == "--help" || "$1" == "help" ]] && echo "$COMMAND_HELP" && return

    local message="$1"
    [ -z "$message" ] && message="Confirmation required"

    local default="$2"
    # To lower case
    default=$(echo "$default" | tr '[:upper:]' '[:lower:]')

    if [[ "$default" == "y" ]] || [[ "$default" == "yes" ]]; then
        default="y"
        message="$message [Y/n]: "
    else
        default="n"
        message="$message [y/N]: "
    fi

    local result
    if [[ $SHELL == *"zsh"* ]]; then
        # vared -p "$message" 'result'
        echo -n "$message"
        read -r result
    else
        read -p "$message" result
    fi

    if [ -z "$result" ]; then
        [ "$default" = "y" ] && return 0 || return 1
    fi

    # To lower case
    result=$(echo "$result" | tr '[:upper:]' '[:lower:]')
    [ "$result" = "y" ] && return 0 || return 1
}

_do_command $@
