#!/bin/bash

COMMAND_DESCRIPTION="Print help information for the given command."

COMMAND_HELP="\
Print help information for the given command.
Usage:
    :help [command]
"

_do_command() {
   [[ "$1" == "--help" || "$1" == "help" ]] && echo "$COMMAND_HELP" && return

    if [ -z "$1" ]; then
        echo "$COMMAND_HELP"
        return 1
    fi

    local command="$@"

    help_cmd="$LETDEV_HOME/get-command-variable.sh '$command' COMMAND_HELP"
    local command_help=$(eval "$help_cmd")

    [ -n "$command_help" ] && echo "$command_help" && return

    # Try to get help from the command itself and print it if the command has executed successfully
    local command_help=$($command --help 2>&1)
    if [ $? -eq 0 ]; then
        echo "$command_help"
        return
    fi
}

_do_command "$@"
