#!/usr/bin/env bash

COMMAND_DESCRIPTION="Run command in a specific directory"

COMMAND_HELP="\
This script is used to run a command in a specific directory.
Usage:
    :in <dir> <command> [args]
Example:
    :in /path/to/dir ls -l
"

_do_command() {
  # Show help on --help
  if [[ "$#" -eq 0 || "$1" == "--help" || "$1" == "help" ]]; then
    echo "$COMMAND_HELP"
    return
  fi

    TARGET_DIR="$1"
    shift
    args="$@"

    if [[ ! -d "$TARGET_DIR" ]]; then
        echo "Directory '$TARGET_DIR' does not exist."
        return 1
    fi

    (
        cd "$TARGET_DIR"
        bash -c "$args"
    )
}

_do_command $@
