#!/usr/bin/env bash

COMMAND_DESCRIPTION="Display directory tree recursively with files and directories"

COMMAND_HELP="\
Display directory tree recursively with files and directories.
Usage: 
    :lstree [path]
Example:
    :lstree /path/to/dir
"

_do_command() {
    # Show help on --help
    if [[ "$#" -eq 0 || "$1" == "--help" || "$1" == "help" ]]; then
        echo "$COMMAND_HELP"
        return
    fi

    local lstree="ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'"
    eval "$lstree"
}

_do_command "$@"
