#!/usr/bin/env bash

COMMAND_DESCRIPTION="Chain of greps"

COMMAND_HELP="\
Chain of greps (grep $1 | grep $2 | ...).

Usage:
    :match [--with-first-row[s=n]] <contains1> <contains2> <!not_contains1> ...

    Use regular expression (in all patterns)

Arguments:
    contains - pattern which should present in the output
    !not_contains - pattern which should not present in the output

Options:
    --with-first-row print the first line of the input in any case before the grep output
    --with-first-rows[=n]: print the first lines of the input in any case before the grep output
      can be used with arguments or without them
      if used without arguments, the first line will be printed

Example:
    ls | :match .txt|.md !tmp
"

# Escape all special characters in the patern, so it can be used in the grep, including . () | and others
_escape_patern() {
    # Now escaping only . | () 
    echo "$1" | sed 's!\([.|()]\)!\\\1!g'
}

_do_command() {
    if [ "$1" = "--help" ] || [ "$1" = "help" ]; then
        echo "$COMMAND_HELP"
        return
    fi

    :grep --regexp "$@"
}

_do_command "$@"
