#!/usr/bin/env bash

COMMAND_DESCRIPTION="deletes all files and directories in the specified directory"

COMMAND_HELP="\
This script deletes all files and directories in the specified or current directory, including hidden files and directories.
Usage: 
    :rm-all [dir]
Example:
    :rm-all /path/to/dir
"

_do_command() {
    [[ "$1" == "--help" || "$1" == "help" ]] && echo "$COMMAND_HELP" && return

    TARGET_DIR="${1:-.}"

    if [[ ! -d "$TARGET_DIR" ]]; then
        echo "Directory '$TARGET_DIR' does not exist."
        return 1
    fi

    # Get the user confirmation
    read -p "Are you sure you want to delete all files and directories in '$TARGET_DIR'? (y/n): " -n 1 -r
    echo ""

    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Operation cancelled."
        return 1
    fi

    (
        cd "$TARGET_DIR"
        # Delete all files and directories in the specified directory except the current and parent directories
        find "$TARGET_DIR" -mindepth 1 -delete
    )

    echo "All files and directories in '$TARGET_DIR' have been deleted."
}

_do_command $@
