#!/usr/bin/env bash

COMMAND_DESCRIPTION="Split stdin lines into multiple lines or columns with a delimiter"

COMMAND_HELP='\
Split every line of stdin into multiple lines or columns with a delimiter.

Usage:
    :split [delimiter] [new_delimiter]

Arguments:
    delimiter: delimiter between the grouped lines. 
               Default is space
    new_delimiter: delimiter between the columns in the line. 
                   Default is tab

Example:
    :split            # Split every line by space into separated columns
    :split , "\n"     # Split every line by comma into separated lines
'

_do_command() {
    # Show help on --help
    if [[ "$1" == "--help" || "$1" == "help" ]]; then
        echo "$COMMAND_HELP"
        return
    fi

    local delimiter="$1"
    [[ -z "$delimiter" ]] && delimiter=" " || shift

    local new_delimiter="$1"
    [[ -z "$new_delimiter" ]] && new_delimiter=$'\t' || shift

    while IFS= read -r line; do
        local first=true
        echo "$line" | tr "$delimiter" '\n' | while IFS= read -r word; do
            if [ "$first" = true ]; then
                first=false
            else
                echo -n -e "$new_delimiter"
            fi
            echo -n "$word"
        done
        echo ""
    done
}

_do_command "$@"
