#!/bin/bash

COMMAND_DESCRIPTION="Simple key-value storage"

COMMAND_HELP="\
Simple key-value storage implementation.

Usage: 
    :storage ls                             - list all keys and values
    :storage get <key> [default-value]      - get the value of the key or default value if not found
    :storage set <key> [new-value]          - set new value for the key or remove the key
    :storage has <key>                      - check if the key exists, return 0 or 1

Arguments:
    key: the key to store or retrieve
    new-value: the new value to store
    default-value: the default value to return if the key is not found

Example:
    :storage get my-key # get the value of the key or empty string if not found
    :storage get my-key default-value # get the value of the key or default value if not found

    :storage set my-key new-value # set new value for the key
    :storage set my-key # remove the key

    :storage has my-key # check if the key exists
"


_get_value() {
    local key="$1"
    local default_value="$2"

    if [ -z "$key" ]; then
        echo "Missing key" >&2
        return 2
    fi

    if letdev_storage_has "$key"; then
        letdev_storage_get "$key"
    else
        [ -n "$default_value" ] && echo "$default_value"
        return 1
    fi
}

_set_value() {
    local key="$1"
    local new_value="$2"

    if [ -z "$key" ]; then
        echo "Missing key" >&2
        return 3
    fi

    if [ -z "$new_value" ]; then
        [ letdev_storage_has "$key" ] && letdev_storage_remove "$key" || return 1
        return
    fi

    letdev_storage_set "$key" "$new_value"
}

_do_command() {
    [[ "$1" == "--help" || "$1" == "help" ]] && echo "$COMMAND_HELP" && return

    local command="$1"
    [ -n "$command" ] && shift
    local key="$1"
    [ -n "$key" ] && shift
    local value="$1"
    [ -n "$value" ] && shift

    case $command in
        ls|list)
            letdev_storage_list
            ;;
        get)
            _get_value "$key" "$value"
            ;;
        set)
            _set_value "$key" "$value"
            ;;
        has)
            if [ -z "$key" ]; then
                echo "Missing key"
                return 1
            fi
            letdev_storage_has "$key"
            ;;
        *)
            # Simple mode

            value="$key"
            key="$command"

            if [ -z "$key" ]; then
                letdev_storage_list
            elif [ -z "$value" ]; then
                _get_value "$key"
            else
                _set_value "$key" "$value"
            fi
            ;;
    esac
}

_do_command "$@"
