#!/bin/bash

COMMAND_DESCRIPTION="Simple key-value storage"

COMMAND_HELP="\
Simple key-value storage implementation.

Usage: 
    :storage ls                             - list all keys and values
    :storage get <key> [default-value]      - get the value of the key or default value if not found
    :storage set <key> [new-value]          - set new value for the key or remove the key
    :storage has <key>                      - check if the key exists, return 'true' or 'false' 

    :storage [status]                       - check the status of the storage, default command
    :storage start                          - start the storage
    :storage stop                           - stop the storage
    :storage restart                        - restart the storage
    :storage pid                            - get the process ID of the storage

    :storage help                           - display this help

Arguments:
    key: the key to store or retrieve
    new-value: the new value to store
    default-value: the default value to return if the key is not found

Example:
    :storage get my-key # get the value of the key or empty string if not found
    :storage get my-key default-value # get the value of the key or default value if not found

    :storage set my-key new-value # set new value for the key
    :storage set my-key # remove the key

    :storage has my-key # check if the key exists
"

_list_values() {
    if letdev_storage_started; then
        letdev_storage_list
    else
        echo "Storage is not started" >&2
    fi
}

_get_value() {
    local key="$1"
    local default_value="$2"

    if [ -z "$key" ]; then
        echo "Missing key" >&2
        return 3
    fi

    if letdev_storage_started; then
        if letdev_storage_has "$key"; then
            letdev_storage_get "$key"
        else
            [ -n "$default_value" ] && echo "$default_value"
            return 1
        fi
    else
        echo "Storage is not started" >&2
        return 2
    fi
}

_set_value() {
    local key="$1"
    local new_value="$2"

    if [ -z "$key" ]; then
        echo "Missing key" >&2
        return 3
    fi

    if letdev_storage_started; then
        if [ -z "$new_value" ]; then
            [ letdev_storage_has "$key" ] && letdev_storage_remove "$key" || return 1
            return
        fi

        letdev_storage_set "$key" "$new_value"
    else
        echo "Storage is not started" >&2
        return 2
    fi
}

_do_command() {
    [[ "$1" == "--help" || "$1" == "help" ]] && echo "$COMMAND_HELP" && return

    local command="$1"
    [ -n "$command" ] && shift
    local key="$1"
    [ -n "$key" ] && shift
    local value="$1"
    [ -n "$value" ] && shift

    case $command in
        status)
            letdev_storage_status
            ;;
        start)
            if letdev_storage_started; then
                echo "Storage is already started"
            else
                letdev_storage_start
                echo "Storage has been started"
            fi
            ;;
        stop)
            letdev_storage_stop
            echo "Storage has been stopped and all resources have been released"
            ;;
        restart)
            letdev_storage_stop
            letdev_storage_start
            echo "Storage has been restarted"
            ;;
        pid)
            letdev_storage_pid
            ;;
        ls|list)
            _list_values
            ;;
        get)
            _get_value "$key" "$value"
            ;;
        set)
            _set_value "$key" "$value"
            ;;
        has)
            if letdev_storage_started; then
                if [ -z "$key" ]; then
                    echo "Missing key"
                    return 1
                fi
                letdev_storage_has "$key"
            else
                echo "Storage is not available"
            fi
            ;;
        *)
            # Simple mode

            value="$key"
            key="$command"

            if [ -z "$key" ]; then
                _list_values
            elif [ -z "$value" ]; then
                _get_value "$key"
            else
                _set_value "$key" "$value"
            fi
            ;;
    esac
}

_do_command "$@"
