#!/usr/bin/env bash

COMMAND_DESCRIPTION="View the contents of a file"

COMMAND_HELP="\
View the contents of the specified file with colorized syntax highlighting.
Usage:
    :view <file>
Example:
    :view /path/to/file
"

_install() {
  # Check the operating system
  if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    # Check if bat is installed
    if [ ! command -v batcat &> /dev/null ] && [ ! command -v bat &> /dev/null ]; then
      # Install bat using the package manager
      sudo apt install bat
      echo "Bat installed successfully"
    else
      echo "Bat is already installed"
    fi
  elif [[ "$OSTYPE" == "darwin"* ]]; then
    # Check if brew is installed
    if ! command -v brew &> /dev/null; then
      echo "Homebrew is not installed. Please install Homebrew before running this script."
      return
    fi

    # Check if bat is installed
    if ! command -v bat &> /dev/null; then
      # Install bat using the package manager
      brew install bat
      echo "Bat installed successfully"
    else
      echo "Bat is already installed"
    fi
  else
    echo "Unsupported operating system"
    return
  fi
}

_do_command() {
  # Show help on --help
  if [[ "$#" -eq 0 || "$1" == "--help" || "$1" == "help" ]]; then
    echo "$COMMAND_HELP"
    return
  fi

  if [[ "$1" == "--install" ]]; then
    _install
    return
  fi

  local cmd=''
  local file="$1"

  # Check if the file exists
  if [[ ! -f "$file" ]]; then
    echo "File '$file' not found"
    return
  fi

  # Check if bat is installed
  if command -v batcat &> /dev/null; then
    cmd='batcat'
  elif command -v bat &> /dev/null; then
    cmd='bat'
  else
    echo "Bat is not installed. Please, use ': :view --install' command to install it and view the file with colorized syntax highlighting"
    cmd='more'
  fi

  $cmd $file
}

_do_command $@
