#!/bin/bash

COMMAND_DESCRIPTION="Initialize the current folder as the let.dev project folder."

COMMAND_HELP="\
Initialize the current folder as the let.dev project folder.
Usage:
  :let-dev:init-project-folder [profile]\
"

_do_command() {
    profile="$1"

    [ -z "$profile" ] && profile=$(:ask "Enter profile name (default is '$LETDEV_PROFILE')")
    [ -z "$profile" ] && profile=$LETDEV_PROFILE

    script_dir="./.let-dev/$profile"

    mkdir -p "$script_dir/commands"

    echo "let.dev initialized for profile $profile"
}

_do_command "$@"
