#!/bin/bash

COMMAND_DESCRIPTION="Initialize the current folder as the let.dev project folder."

COMMAND_HELP="\
Initialize the current folder as the let.dev project folder.
Usage:
    :let-dev:init-project-folder [profile]
"

_do_command() {
    profile="$1"

    [ -z "$profile" ] && profile=$(:ask "Enter profile name (default is '$LETDEV_PROFILE')")
    [ -z "$profile" ] && profile=$LETDEV_PROFILE

    script_dir="./.let-dev/$profile"

    mkdir -p "$script_dir/commands"
    mkdir -p "$script_dir/path"

    # Create example script
    local script='
#!/bin/bash

# This is an example command script

COMMAND_HELP="\\
Example command to show how to create a command script.
Usage:
    : :example
"

echo "Hello, world!"
'

    echo -en "$script" > "$script_dir/commands/example"

    echo "let.dev initialized for profile $profile"
}

_do_command "$@"
