#!/bin/bash

COMMAND_DESCRIPTION="Reload LetDev shell settings"

COMMAND_HELP="\
Reload LetDev shell settings.
Usage: :let-dev:reload\
"

_do_command() {
    source $LETDEV_HOME/init-shell.sh
}

_do_command "$@"
