#!/bin/bash

COMMAND_DESCRIPTION="Create new command to change directory to a specific location"

COMMAND_HELP="\
Create new command to change directory to a specific location.
If location is not provided, the current directory will be used.
Usage:
    :let-dev:save-location <alias_name> [location]
"

_do_command() {
    alias_name="$1"
    [ -z "$alias_name" ] && alias_name=$(basename $PWD)

    location="$2"
    [ -z "$location" ] && location="$PWD"

    script_name="$alias_name"
    script_path="$LETDEV_HOME/profiles/$LETDEV_PROFILE/commands/cd/$script_name"

    echo "Add alias ':cd:$alias_name' which will change directory to '$location'"

    [ -f "$script_path" ] && echo "Alias with the name ':cd:$alias_name' already exists" && return

    mkdir -p "$LETDEV_HOME/profiles/$LETDEV_PROFILE/cd"

    touch "$script_path"
    chmod +x $script_path

    echo "#! /bin/bash" >"$script_path"
    echo "" >>"$script_path"
    echo "cd $location" >>"$script_path"

    # eval :let-dev:reload
}

_do_command "$@"
