#!/bin/bash

COMMAND_DESCRIPTION="Update local LetDev from the git remote"

COMMAND_HELP="\
Update local LetDev from the git remote repository with git pull.
Usage: :let-dev:update-from-git"

_do_command() {
    local current_dir=$(pwd)
    cd $LETDEV_HOME
    git pull
    cd $current_dir
}

_do_command "$@"
