#!/bin/bash

COMMAND_DESCRIPTION="Reload LetDev shell settings"

COMMAND_HELP="\
Reload LetDev shell settings.
Usage: 
    :letdev:reload
"

_do_command() {
    source $LETDEV_HOME/init-shell.sh
    echo "letdev shell settings reloaded"
}

_do_command "$@"
