#!/bin/bash

script_name="$1"
script_full_name="~/.@/cd/$script_name"
alias_name="@@-$script_name"
command="$2"

echo -n  "Add alias '$alias_name' for the '$command' command"
pushd ~/.@ > /dev/null

echo "$command" > "$script_name"
chmod +x $script_name
alias $alias_name="source $script_full_name"

popd > /dev/null
echo "  ..  done"