#!/bin/bash

alias_name="$1"
script_name="$alias_name"
script_path="$HOME/aliases/cd/$script_name"

location="$2"
[ -z "$location" ] && location="$PWD"

echo "Add alias ':cd:$alias_name' which change current folder to the '$location'"

mkdir -p "$HOME/aliases/cd"

touch "$script_path"
chmod +x $script_path
alias ":cd:$alias_name"="source $script_path"

echo "#! /bin/bash" > "$script_path"
echo "" >> "$script_path"
echo "cd $location" >> "$script_path"
