#!/usr/bin/env bash

COMMAND_DESCRIPTION="Start bash in a running container"

COMMAND_HELP="\
Connect to a running container and start a bash.

Usage:
    :docker:container:bash [container_id | container_name]

    If container_id is not provided, it will ask for it.
    If command is not provided, it will default to '/bin/bash'.

Example:
    :docker:container:bash
    :docker:container:bash my-container
"

_do_command() {
    if [ "$1" = "--help" ] || [ "$1" = "help" ]; then
        echo "$COMMAND_HELP"
        return
    fi

    :docker:container:exec $1 bash
}

_do_command "$@"
