#!/usr/bin/env bash

COMMAND_DESCRIPTION="Start sh shell in a running container"

COMMAND_HELP="\
Connect to a running container and start a sh shell.

Usage:
    :docker:container:sh [container_id | container_name]

    If container_id is not provided, it will ask for it.
    If command is not provided, it will default to '/bin/sh'.

Example:
    :docker:container:sh
    :docker:container:sh my-container
"

_do_command() {
    if [ "$1" = "--help" ] || [ "$1" = "help" ]; then
        echo "$COMMAND_HELP"
        return
    fi

    :docker:container:exec $1 sh
}

_do_command "$@"
