#!/usr/bin/env bash

COMMAND_DESCRIPTION="Docker containers ports"

COMMAND_HELP="\
Get list of Docker containers ports.
Usage:
    :docker:container:ports
"

_do_command() {
    if [ "$1" = "--help" ] || [ "$1" = "help" ]; then
        echo "$COMMAND_HELP"
        return
    fi

    docker ps -a --format "table {{.ID}}\t{{.Names}}\t{{.Ports}}\t{{.Status}}" $@
}

_do_command "$@"
