#!/bin/bash

COMMAND_DESCRIPTION="GPU Information"

COMMAND_HELP="\
Display GPU Information
Usage: 
    :info:gpu
"

_do_command() {
    echo "GPU Information:"
    if [ -x "$(command -v nvidia-smi)" ]; then
        nvidia-smi
    else
        echo "Cannot find GPU information"
    fi
}

_do_command $@
