#!/bin/bash

COMMAND_DESCRIPTION="HDD Information"

COMMAND_HELP="\
Display Hard Disk Information and Filesystem Disk Space Usage
Usage: :info:hdd
"

_do_command() {
    echo "Hard Disk Information:"
    df -h
    echo ""

    echo "Filesystem Disk Space Usage:"
    df -h
    echo ""
}

_do_command $@
