#!/bin/bash

COMMAND_DESCRIPTION="Mounted Filesystems"

COMMAND_HELP="\
Display mounted filesystems information
Usage: 
    :info:mounted
"

_do_command() {
    echo "Mounted Filesystems:"
    mount | column -t
}

_do_command $@

