#!/bin/bash

# Install htop if not installed with system package manager
if ! [ -x "$(command -v htop)" ]; then
    if command -v apt &>/dev/null; then
        sudo apt install htop
    elif command -v dnf &>/dev/null; then
        sudo dnf install htop
    elif command -v brew &>/dev/null; then
        brew install htop
    else
        # Try to use top
        top
        return
    fi
fi

htop
