#!/usr/bin/env bash
# set -euo pipefail

# This script returns the value of the specified variable from the .env file

_do_command() {
  if [[ "$1" = "--help" ]]; then
    echo "Read environment variable value from .env or .sh file."
    echo "Usage:"
    echo "  :$0 <env_file> <variable_name> [--find|--execute]"
    echo "Options:"
    echo "  --find (default): Find the value of the variable in the text of the file (grep)"
    echo "  --execute: Get the value of the environment variable after the file execution as a shell script (source)"
    echo "Example:"
    echo "  :$0 .env MY_ENV_VAR"
    echo "  :$0 .env MY_ENV_VAR --execute"
    return
  fi

  if [[ "$#" -lt 2 ]]; then
    # echo "Invalid number of arguments"
    return 1
  fi

  local ENV_FILE="$1"
  local VARIABLE_NAME="$2"
  local MODE="${3:-"--find"}"

  if [ ! -f "$ENV_FILE" ]; then
    # echo "File $ENV_FILE does not exist"
    return 1
  fi

  if [[ "$MODE" = "--execute" ]]; then
    (
      set -a
      source $ENV_FILE
      set +a
      eval echo \$$VARIABLE_NAME
    )
  elif [[ "$MODE" = "--find" ]]; then
    local VARIABLE_VALUE=$(awk -F '=' -v var="$VARIABLE_NAME" '$1==var {print $2}' $ENV_FILE)
    echo $VARIABLE_VALUE
  else
    # echo "Invalid mode"
    return 1
  fi
}

_do_command "$@"
