#!/usr/bin/env bash
# set -euo pipefail

# This script deletes all files and directories in the specified or current directory, including hidden files and directories.

if [[ "$1" = "--help" || "$#" -lt 1 ]]; then
    echo "Delete all files and directories in the specified or current directory."
    echo "Usage:"
    echo "  :rm-all [dir]"
    echo "Example:"
    echo "  :rm-all /path/to/dir"
    return
fi

TARGET_DIR="${1:-.}"

if [[ ! -d "$TARGET_DIR" ]]; then
    echo "Directory '$TARGET_DIR' does not exist."
    return 1
fi

# Get the user confirmation
read -p "Are you sure you want to delete all files and directories in '$TARGET_DIR'? (y/n): " -n 1 -r
echo ""

if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Operation cancelled."
    return 1
fi

(
    cd "$TARGET_DIR"
    # Delete all files and directories in the specified directory except the current and parent directories
    find "$TARGET_DIR" -mindepth 1 -delete
)

echo "All files and directories in '$TARGET_DIR' have been deleted."
