#!/usr/bin/env bash
# set -euo pipefail

COMMAND_DESCRIPTION="Edit Nginx configuration"
COMMAND_HELP="\
Open Nginx service configuration file (nginx.conf) in the preferred text editor
"

_do_command() {

    local FILE_TO_OPEN="/etc/nginx/nginx.conf"

    # Check if Nginx is installed
    if ! command -v nginx &> /dev/null
    then
        echo "Nginx service is not installed"
        return
    fi

    if [ ! -f "$FILE_TO_OPEN" ]; then
        echo "Nginx service is installed, but $FILE_TO_OPEN was not found"
        return
    fi

    local hash_before=$(sha256sum "$file")
    : :config:nginx
    local hash_after=$(sha256sum "$file")

    if [[ "$hash_before" != "$hash_after" ]]; then
        echo "Nginx configuration updated"

        # Reload Nginx if it is running
        if sudo systemctl is-active --quiet nginx; then
            echo "Nginx service is running, reloading..."
            sudo systemctl reload nginx
            echo "Nginx service reloaded"
        fi
    else
        echo "Nginx configuration was not changed"
    fi
}

_do_command "$@"
