#!/usr/bin/env bash
# set -euo pipefail

# Restore backup of nginx.conf file

# Check if nginx is installed
if ! command -v nginx &> /dev/null
then
    echo "nginx is not installed"
    return
fi

nginx_conf="/etc/nginx/nginx.conf"

backup_path=${1:-"/etc/nginx/nginx.conf.bak"}

# if we get only the directory path, append the file name
if [ -d "$backup_path" ]; then
    backup_path="$backup_path/nginx.conf.bak"
fi

# If we get only the file name, append the /etc/nginx/ path
if [ ! -d "$(dirname $backup_path)" ]; then
    backup_path="/etc/nginx/$backup_path"
fi

# Check if the backup file exists
if [ ! -f "$backup_path" ]; then
    echo "Backup file does not exist at $backup_path"
    return
fi

# Restore the backup
sudo cp "$backup_path" "$nginx_conf"

echo "nginx.conf is restored from $backup_path"
