#!/usr/bin/env bash
# set -euo pipefail

COMMAND_DESCRIPTION="Make request to the Google DNS"

COMMAND_HELP="\
Make request to the Google DNS.
"

_do_command() {
    [[ "$1" == "--help" || "$1" == "help" ]] && echo "$COMMAND_HELP" && return

    # Проверить разрешение через внешний DNS (Google)
    dig $1 @8.8.8.8
}

_do_command "$@"
