#!/usr/bin/env bash
# set -euo pipefail

COMMAND_DESCRIPTION="Reset local DNS cache"

COMMAND_HELP="\
Reset local DNS cache.
"

_do_command() {
    [[ "$1" == "--help" || "$1" == "help" ]] && echo "$COMMAND_HELP" && return

    local OS="$(uname)"
    if [[ "$OS" == "Linux" ]]; then
        echo "Unsupported OS: $OS"
    elif [[ "$OS" == "Darwin" ]]; then
        # Очистить DNS-кеш macOS
        sudo dscacheutil -flushcache
        sudo killall -HUP mDNSResponder
    else
        echo "Unsupported OS: $OS"
        return
    fi
}

_do_command "$@"
